### ISSUE TITLE
Setup tests with NodeJS

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-rln#25]
Testing with Karma takes time locally as it needs to bundle every time.

Having the option to use node would make the feedback loop shorter when developing.

**Comment by fryorcraken** [comment]
Not straightforward, would need to provide 2 bundles in the zerokit-wasm package.

**Comment by chair28980** [comment]
This work will be covered within the scop of the `test-automation-rln` work. Other portions of this work have been completed and critical coverage exists already in the rln work done previously in js-waku.
