### ISSUE TITLE
Reduce chances of loosing RLN credentials.

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-rln#28]
## Problem

Credentials are purely generated from entropy, meaning that if a user lose access to their key, then they lose access to their RLN membership.

### A. Seed derivation from signature

1. Make user sign message `M`: `The signature of this message will be used to generate your RLN credentials. Ensure that this signature is only shared with the RLN dApp.`
2. Hash signature
3. Use hash as seed for RLN credentials generation

As long as the user has access to their Ethereum private key, they can regenerate their credentials.

They also need to be able to retrieve their membership id.

To do so:
1. Look at past transactions sent from this wallet
2. Find transaction sent to RLN contract
3. Check receipt to get the membership id

### B. Secure storage of credentials in cryptkey-like extension

Another strategy is to store the credentials in an extensions.

## Acceptance Criteria

- [ ] Implement A

## Note

Zerokit now supports seeded keygen: https://github.com/vacp2p/zerokit/pull/56

Strategy B can be done at a later stage.

**Comment by fryorcraken** [comment]
@staheri14 @s1fr0 please clarify:

1. What hash should be used to hash the signature before feeding it to zerokit as a seed?
2. What message would you prefer we use?
3. Most ZK projects I have see use eth personal sign. Do we want to also use it? Should we try to use EIP-712 instead? It might have better security if the wallet checks the `name` in the data struct to sign against the domain name of the app
4. Discussion about a password and nonce were made, do we want to implement either? Feel free to forward me to an RFC if I missed it.
5. I assume that the membership id is present in the event logs of the registration transaction, am I correct? @richard-ramos ?

**Comment by richard-ramos** [comment]
> I assume that the membership id is present in the event logs of the registration transaction, am I correct? @richard-ramos ?

Yes, it's the `index` parameter of the event `MemberRegistered(uint256 pubkey, uint256 index)`

**Comment by staheri14** [comment]
@fryorcraken  for 2 and 4, the contract address and the nonce are definitive. With nonce we allow multiple registrations to the same membership contract. However, for the password, we yet did not get to an agreement. To me still it makes sense to have an app-level password to make sure the same seed (hence rln credentials) will not be derived by a malicious irrelevant application.

**Comment by fryorcraken** [comment]
Note that it would make more sense to look at the merkle tree to recover the membership id. See https://github.com/status-im/nwaku/issues/1278#issuecomment-1308480846
