### ISSUE TITLE
Contract handling helper

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-rln#29]
## Problem

Retrieving membership details and adding them to the `RlnInstance` is something that any user of js-rln should do and are likely to copy-paste from https://github.com/waku-org/js-waku-examples/blob/b6d9942b113e51298ba9e4405997c3dc52bec908/rln-js/index.html#L259

Same re listening to contract event add new memberships to `RlnInstance`.

Same re registering membership in contract: https://github.com/waku-org/js-waku-examples/blob/b6d9942b113e51298ba9e4405997c3dc52bec908/rln-js/index.html#L287

## Solution

Provide a function helper that does that.

2 possibilities:
1. Function helper uses `ethers`, hence we can set `ethers` as an optional dependency
2. Function helper gets passed an object that implement an interface so to give the choice to the user between `ethers` and `web3js`.

Not sure (2) is straight forward, might be easier to just go with (1) for now

## Acceptance Criteria

- [x] User can call 1 function to retrieve members from contract, add them to `RlnInstance` and add new members to `RlnInstance` by listening to contract
- [x] User can call 1 function to add credentials to contract.

**Comment by weboko** [comment]
I am still to able to determine good API to cover this so @fryorcraken do you see other points for improvement here?

**Comment by fryorcraken** [comment]
I see you have done improvement already with #43 . Let's use it in the examples and see how it looks.

**Comment by weboko** [comment]
Ok, so I'll define as follow up item next thing:
- [ ] use contract abstraction in the example;
