### ISSUE TITLE
fix(rln): convert id commitments to uint256 from LE on register

### ISSUE THREAD

**Issue by s1fr0** [waku-org/js-rln#37]
# Problem

Zerokit generates and serializes id keys and the corresponding id commitments in little endian. The membership smart contract, instead, expects id commitments to be uint256. 

This means that when registering an id commitment generated from zerokit, js-rln should ensure that the value registered corresponds to the uint256 conversion from the id commitment in little endian. 

This is not the case at the moment, where no endianess conversion is implemented and commitments are registered "as they are" to the contract. This has the consequences that proofs might result invalid when verified from other implementations.

# Example
Zerokit generates
```
Key: b20ea77f8d11182df896021c9f1c6f82e21694a44ecf1b030461a5b4fc581817
Commitment: b69a4ee2e32152c4b4bf3b677d160b9d19d9ab043a281dd39cca84a6eadafa11
```
both visualized in their little-endian representation. The value that should be registered to the smart contract is
```
Commitment: 0x11fadaeaa684ca9cd31d283a04abd9199d0b167d673bbfb4c45221e3e24e9ab6
```
and not  `0xb69a4ee2e32152c4b4bf3b677d160b9d19d9ab043a281dd39cca84a6eadafa11` as happens now.

# Acceptance criteria
- [ ] Fix endianess conversion;
- [ ] (Nice to have) visualize `Key` and `Commitment` as the uints they represents (i.e. with bytes reversed).

**Comment by staheri14** [comment]
A few questions:
Is this happening just in the js-rln? 
Does the inconsistency happen at the Merkle tree level? 
Does it require update on the wire format? is the e.g., Merkle tree root exchanged as part of `RateLimitProof` also encoded in LE?
> Fix endianess conversion
Where should this fix happen? in js-rln?

**Comment by staheri14** [comment]
So,

1. The contract should hold the unit256 representation of the id commitments with LE encoding. 
2. The Merkle tree roots should be also in LE format.  
3. And the zkSNARK proofs should be generated using the id commitment in LE format. 

What is the exact part that js-rln is doing inconsistent with the above?

**Comment by fryorcraken** [comment]
@s1fr0 If js-rln registers the wrong value in the contract, how come proofs generated by js-rln are accepted by nwaku when the creds registered in the contract are incorrect?
