### ISSUE TITLE
Better rationale of repo and diff with existing rlnjs

### ISSUE THREAD

**Issue by oskarth** [waku-org/js-rln#39]
Currently https://github.com/Rate-Limiting-Nullifier/rlnjs has existed for a while, and we created a very similar `js-rln` repo.

It should be clear (a) why there's another repo and (b) what is different/similar

(I know ~roughly why in terms of Zerokit etc, but it should be clear for new people and also reference existing work).

cc @fryorcraken

**Comment by fryorcraken** [comment]
Need to add README to specify that js-rln is a wrapper to zerojit's RLN feature (exported as WASM for the browser). that is opiniated to Waku.

In addition to allowing:
- generation of credentials
- seeded generation of credentials (ie, from a signature done using an Etheruem account)

It implements js-waku interfaces to enable:
- attaching proof to ongoing waku messages
- API to check proof of incoming waku messages
