### ISSUE TITLE
Support Import and Export of RLN Credentials

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-rln#48]
See https://github.com/waku-org/nwaku/issues/1278#issuecomment-1423319660

Cc @s1fr0

**Comment by weboko** [comment]
Let's align on the outcome of this issue and particular API to be implemented.

**Comment by fryorcraken** [comment]
Support the import of export of ZK credentials in RLN js as implemented in https://github.com/waku-org/nwaku/pull/1285

Do note that I think we may want to split the current rln-js example in two:
1. uses wallet signature
2. Uses this (and possibly deprecated old import)

**Comment by weboko** [comment]
Resolving with Keystore supporting export functionality. 
https://github.com/waku-org/js-rln/pull/70
